### ISSUE TITLE
ST_Transform doesn't work on hadoop cluster

### ISSUE THREAD

**Issue by xiaocai2333** [zilliztech/arctern#282]
It works fine for a single machine
but for the entire cluster, it does not
eg: spark-submit --master yarn 

output:
Driver stacktrace:
20/03/16 02:32:04 INFO DAGScheduler: Job 0 failed: sql at NativeMethodAccessorImpl.java:0, took 3.073324 s
Traceback (most recent call last):
  File "/home/zilliz/benchmark/json_test.py", line 262, in <module>
    run_st_point(spark)
  File "/home/zilliz/benchmark/json_test.py", line 56, in run_st_point
    exec_func(spark, df, sql, "points")
  File "/home/zilliz/benchmark/json_test.py", line 41, in exec_func
    ret, duration = _exec_func()
  File "/home/zilliz/benchmark/json_test.py", line 25, in wrapper
    result = func(*arg)
  File "/home/zilliz/benchmark/json_test.py", line 39, in _exec_func
    cache(spark, rs, rs_name)
  File "/home/zilliz/benchmark/json_test.py", line 18, in cache
    spark.sql("CACHE table %s"%t_name)
  File "/home/zilliz/hadoop_spark3_p2/python/lib/pyspark.zip/pyspark/sql/session.py", line 806, in sql
  File "/home/zilliz/hadoop_spark3_p2/python/lib/py4j-0.10.8.1-src.zip/py4j/java_gateway.py", line 1285, in __call__
  File "/home/zilliz/hadoop_spark3_p2/python/lib/pyspark.zip/pyspark/sql/utils.py", line 98, in deco
  File "/home/zilliz/hadoop_spark3_p2/python/lib/py4j-0.10.8.1-src.zip/py4j/protocol.py", line 326, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o22.sql.

**Comment by nezha2017** [comment]
does every nodes in the cluster set these two environment variables
```bash
export GDAL_DATA=/path/to/conda/envs/zgis_dev/share/gdal
export PROJ_LIB=/path/to/conda/envs/zgis_dev/share/proj
```
