### ISSUE TITLE
vega_pointmap is error when opacity is 0 or 1, it must be 1.0 & 0.0

### ISSUE THREAD

**Issue by xiaocai2333** [zilliztech/arctern#326]
eg:   
vega = vega_pointmap(1024, 896, [-73.998427, 40.730309, -73.954348, 40.780816], 3, "#2DEF4A", 0, "EPSG:4326")
    baseline = pointmap(res, vega)
or
vega = vega_pointmap(1024, 896, [-73.998427, 40.730309, -73.954348, 40.780816], 3, "#2DEF4A", 1, "EPSG:4326")
    baseline = pointmap(res, vega)

the output is same, it is:

illegal
Traceback (most recent call last):
  File "/home/zc/work/arctern/spark/pyspark/examples/render/nyc_taxi.py", line 141, in <module>
    draw_point_map(spark_session)
  File "/home/zc/work/arctern/spark/pyspark/examples/render/nyc_taxi.py", line 41, in draw_point_map
    baseline = pointmap(res, vega)
  File "/home/zc/miniconda3/envs/arctern/lib/python3.8/site-packages/arctern_pyspark-0.0.0-py3.8.egg/arctern_pyspark/render_func.py", line 49, in pointmap
  File "/home/zc/miniconda3/envs/arctern/lib/python3.8/site-packages/arctern-0.1.0-py3.8-linux-x86_64.egg/arctern/util/vega/pointmap/vega_pointmap.py", line 94, in build
    encode = Marks.Encode(bounding_box=Marks.Encode.Value(self._bounding_box),
  File "/home/zc/miniconda3/envs/arctern/lib/python3.8/site-packages/arctern-0.1.0-py3.8-linux-x86_64.egg/arctern/util/vega/pointmap/vega_pointmap.py", line 46, in __init__
    assert 0
AssertionError

**Comment by xiaocai2333** [comment]
when opacity is 0.0 or 1.0, it is true

**Comment by xiaocai2333** [comment]
And why is it right when opacity is greater than 1.

**Comment by xge-zilliz** [comment]
> And why is it right when opacity is greater than 1.

In opengl, when the transparency is greater than 1, the transparency will be forced to 1.
