### ISSUE TITLE
Memory leaked

### ISSUE THREAD

**Issue by nezha2017** [zilliztech/arctern#399]
## test data
[0_5M_nyc_taxi_data.csv.tar.gz](https://github.com/zilliztech/arctern/files/4396761/0_5M_nyc_taxi_data.csv.tar.gz)

---

## bug info

It would get higher chance to hit this bug if run the test code line by line in the `pyspark` shell, this is the test code.
```python
from arctern_pyspark import register_funcs
spark.conf.set("spark.sql.execution.arrow.pyspark.enabled", "true")
register_funcs(spark)

spark.read.format("csv").option("header",True).option("delimiter",",").schema("VendorID string, tpep_pickup_datetime string, tpep_dropoff_datetime string, passenger_count long, trip_distance double, pickup_longitude double, pickup_latitude double, dropoff_longitude double, dropoff_latitude double, fare_amount double, tip_amount double, total_amount double").load("/tmp/0_5M_nyc_taxi_data.csv").createOrReplaceGlobalTempView("old_nyc_taxi")

spark.sql("select VendorID, to_timestamp(tpep_pickup_datetime,'yyyy-MM-dd HH:mm:ss XXXXX') as tpep_pickup_datetime, to_timestamp(tpep_dropoff_datetime,'yyyy-MM-dd HH:mm:ss XXXXX') as tpep_dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, fare_amount, tip_amount, total_amount from global_temp.old_nyc_taxi where (pickup_longitude between -180 and 180) and (pickup_latitude between -90 and 90) and (dropoff_longitude between -180 and 180) and (dropoff_latitude between -90 and 90)  ").cache().createOrReplaceGlobalTempView("nyc_taxi")

spark.sql(" select *  from global_temp.nyc_taxi where ST_Distance (ST_Transform (ST_Point (dropoff_longitude, dropoff_latitude), 'epsg:4326', 'epsg:3857'), ST_Transform( 'point(-73.95188623976539 40.811208722635484)', 'epsg:4326', 'epsg:3857')) < 363.71614278112816 limit 1").show()
```
if you can't hit the bug at once, just run the last line more times. for my experience, some time, I the bug until I run the last line more than 10 times.
```python
# run this line more time until you hit the bug.
spark.sql(" select *  from global_temp.nyc_taxi where ST_Distance (ST_Transform (ST_Point (dropoff_longitude, dropoff_latitude), 'epsg:4326', 'epsg:3857'), ST_Transform( 'point(-73.95188623976539 40.811208722635484)', 'epsg:4326', 'epsg:3857')) < 363.71614278112816 limit 1").show()
``` 
---
## experiment
I have did some experiments on this bug.
### replace `show()` with `collect()`

**spark.sql(" select *  from global_temp.nyc_taxi where ST_Distance (ST_Transform (ST_Point (dropoff_longitude, dropoff_latitude), 'epsg:4326', 'epsg:3857'), ST_Transform( 'point(-73.95188623976539 40.811208722635484)', 'epsg:4326', 'epsg:3857')) < 363.71614278112816 limit 1").collect()**

### remove `limit 1`

**spark.sql(" select *  from global_temp.nyc_taxi where ST_Distance (ST_Transform (ST_Point (dropoff_longitude, dropoff_latitude), 'epsg:4326', 'epsg:3857'), ST_Transform( 'point(-73.95188623976539 40.811208722635484)', 'epsg:4326', 'epsg:3857')) < 363.71614278112816").show()**

for all these experiments, I run the test code more than 20 times, and never hit the bug.

---
## error message
```txt
spark.sql(" select *  from global_temp.nyc_taxi where ST_Distance (ST_Transform (ST_Point (dropoff_longitude, dropoff_latitude), 'epsg:4326', 'epsg:3857'), ST_Transform( 'point(-73.95188623976539 40.811208722635484)', 'epsg:4326', 'epsg:3857')) < 363.71614278112816 limit 1").show()
20/03/28 16:22:38 ERROR BaseAllocator: Memory was leaked by query. Memory leaked: (524288)
Allocator(stdin reader for /home/cyf/miniconda3/envs/zgis_dev/bin/python) 0/524288/1050624/9223372036854775807 (res/actual/peak/limit)

20/03/28 16:22:38 ERROR TaskContextImpl: Error in TaskCompletionListener
java.lang.IllegalStateException: Memory was leaked by query. Memory leaked: (524288)
Allocator(stdin reader for /home/cyf/miniconda3/envs/zgis_dev/bin/python) 0/524288/1050624/9223372036854775807 (res/actual/peak/limit)

	at org.apache.arrow.memory.BaseAllocator.close(BaseAllocator.java:464)
	at org.apache.spark.sql.execution.python.PythonArrowOutput$$anon$1.$anonfun$new$1(PythonArrowOutput.scala:63)
	at org.apache.spark.sql.execution.python.PythonArrowOutput$$anon$1.$anonfun$new$1$adapted(PythonArrowOutput.scala:59)
	at org.apache.spark.TaskContext$$anon$1.onTaskCompletion(TaskContext.scala:125)
	at org.apache.spark.TaskContextImpl.$anonfun$markTaskCompleted$1(TaskContextImpl.scala:124)
	at org.apache.spark.TaskContextImpl.$anonfun$markTaskCompleted$1$adapted(TaskContextImpl.scala:124)
	at org.apache.spark.TaskContextImpl.$anonfun$invokeListeners$1(TaskContextImpl.scala:137)
	at org.apache.spark.TaskContextImpl.$anonfun$invokeListeners$1$adapted(TaskContextImpl.scala:135)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.TaskContextImpl.invokeListeners(TaskContextImpl.scala:135)
	at org.apache.spark.TaskContextImpl.markTaskCompleted(TaskContextImpl.scala:124)
	at org.apache.spark.scheduler.Task.run(Task.scala:143)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:460)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:463)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
20/03/28 16:22:38 ERROR Executor: Exception in task 4.0 in stage 60.0 (TID 327)
org.apache.spark.util.TaskCompletionListenerException: Memory was leaked by query. Memory leaked: (524288)
Allocator(stdin reader for /home/cyf/miniconda3/envs/zgis_dev/bin/python) 0/524288/1050624/9223372036854775807 (res/actual/peak/limit)

	at org.apache.spark.TaskContextImpl.invokeListeners(TaskContextImpl.scala:145)
	at org.apache.spark.TaskContextImpl.markTaskCompleted(TaskContextImpl.scala:124)
	at org.apache.spark.scheduler.Task.run(Task.scala:143)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:460)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:463)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
20/03/28 16:22:38 WARN TaskSetManager: Lost task 4.0 in stage 60.0 (TID 327, cyf-desktop, executor driver): org.apache.spark.util.TaskCompletionListenerException: Memory was leaked by query. Memory leaked: (524288)
Allocator(stdin reader for /home/cyf/miniconda3/envs/zgis_dev/bin/python) 0/524288/1050624/9223372036854775807 (res/actual/peak/limit)

	at org.apache.spark.TaskContextImpl.invokeListeners(TaskContextImpl.scala:145)
	at org.apache.spark.TaskContextImpl.markTaskCompleted(TaskContextImpl.scala:124)
	at org.apache.spark.scheduler.Task.run(Task.scala:143)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:460)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:463)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

20/03/28 16:22:38 ERROR TaskSetManager: Task 4 in stage 60.0 failed 1 times; aborting job
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cyf/work/spark/python/pyspark/sql/dataframe.py", line 408, in show
    print(self._jdf.showString(n, 20, vertical))
  File "/home/cyf/work/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1304, in __call__
  File "/home/cyf/work/spark/python/pyspark/sql/utils.py", line 98, in deco
    return f(*a, **kw)
  File "/home/cyf/work/spark/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py", line 326, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o1158.showString.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 4 in stage 60.0 failed 1 times, most recent failure: Lost task 4.0 in stage 60.0 (TID 327, cyf-desktop, executor driver): org.apache.spark.util.TaskCompletionListenerException: Memory was leaked by query. Memory leaked: (524288)
Allocator(stdin reader for /home/cyf/miniconda3/envs/zgis_dev/bin/python) 0/524288/1050624/9223372036854775807 (res/actual/peak/limit)

	at org.apache.spark.TaskContextImpl.invokeListeners(TaskContextImpl.scala:145)
	at org.apache.spark.TaskContextImpl.markTaskCompleted(TaskContextImpl.scala:124)
	at org.apache.spark.scheduler.Task.run(Task.scala:143)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:460)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:463)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2054)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2003)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2002)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2002)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:980)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:980)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:980)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2234)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2183)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2172)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:782)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2108)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2129)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2148)
	at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:467)
	at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:420)
	at org.apache.spark.sql.execution.CollectLimitExec.executeCollect(limit.scala:47)
	at org.apache.spark.sql.Dataset.collectFromPlan(Dataset.scala:3556)
	at org.apache.spark.sql.Dataset.$anonfun$head$1(Dataset.scala:2609)
	at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3546)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:100)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:160)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:87)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:763)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3544)
	at org.apache.spark.sql.Dataset.head(Dataset.scala:2609)
	at org.apache.spark.sql.Dataset.take(Dataset.scala:2816)
	at org.apache.spark.sql.Dataset.getRows(Dataset.scala:298)
	at org.apache.spark.sql.Dataset.showString(Dataset.scala:335)
	at sun.reflect.GeneratedMethodAccessor149.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.spark.util.TaskCompletionListenerException: Memory was leaked by query. Memory leaked: (524288)
Allocator(stdin reader for /home/cyf/miniconda3/envs/zgis_dev/bin/python) 0/524288/1050624/9223372036854775807 (res/actual/peak/limit)

	at org.apache.spark.TaskContextImpl.invokeListeners(TaskContextImpl.scala:145)
	at org.apache.spark.TaskContextImpl.markTaskCompleted(TaskContextImpl.scala:124)
	at org.apache.spark.scheduler.Task.run(Task.scala:143)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:460)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:463)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more

>>> 20/03/28 16:22:38 WARN TaskSetManager: Lost task 11.0 in stage 60.0 (TID 334, cyf-desktop, executor driver): TaskKilled (Stage cancelled)
20/03/28 16:22:38 WARN TaskSetManager: Lost task 8.0 in stage 60.0 (TID 331, cyf-desktop, executor driver): TaskKilled (Stage cancelled)
20/03/28 16:22:38 WARN TaskSetManager: Lost task 5.0 in stage 60.0 (TID 328, cyf-desktop, executor driver): TaskKilled (Stage cancelled)
20/03/28 16:22:38 WARN TaskSetManager: Lost task 0.0 in stage 60.0 (TID 323, cyf-desktop, executor driver): TaskKilled (Stage cancelled)
20/03/28 16:22:38 WARN TaskSetManager: Lost task 6.0 in stage 60.0 (TID 329, cyf-desktop, executor driver): TaskKilled (Stage cancelled)
20/03/28 16:22:38 WARN TaskSetManager: Lost task 2.0 in stage 60.0 (TID 325, cyf-desktop, executor driver): TaskKilled (Stage cancelled)
20/03/28 16:22:38 WARN TaskSetManager: Lost task 9.0 in stage 60.0 (TID 332, cyf-desktop, executor driver): TaskKilled (Stage cancelled)
20/03/28 16:22:38 WARN TaskSetManager: Lost task 7.0 in stage 60.0 (TID 330, cyf-desktop, executor driver): TaskKilled (Stage cancelled)
20/03/28 16:22:38 WARN TaskSetManager: Lost task 10.0 in stage 60.0 (TID 333, cyf-desktop, executor driver): TaskKilled (Stage cancelled)
```

**Comment by axelborja** [comment]
Hello @nezha2017, any explanation about this bug ? I encounter the same one ! Thanks

**Comment by nezha2017** [comment]
@axelborja, what's the version of your spark,  3.0.0-preview2 ?

**Comment by axelborja** [comment]
`2.4.5`

**Comment by axelborja** [comment]
@nezha2017 `2.4.5`

**Comment by nezha2017** [comment]
@axelborja , there may be some difference between `2.4.5` and `3.0.0-preview2`. 
 I solved this problem by setting  `spark.sql.execution.arrow.maxRecordsPerBatch`  to `50000`, the default value is `1000`.
```python
spark.conf.set("spark.sql.execution.arrow.maxRecordsPerBatch", "50000")
```
I hope this could give you some help.

**Comment by axelborja** [comment]
@nezha2017 Thanks for sharing. I will try with this conf.

**Comment by koustavmukherjee** [comment]
@axelborja did setting the spark.sql.execution.arrow.maxRecordsPerBatch to 50000 help you get around the issue. I am also facing the same issue.

**Comment by alpcansoydas** [comment]
Upgrade pyspark to newest version
